export default {
    UPDATE_DIVISIONS: 'UPDATE_DIVISIONS',
    UPDATE_BRIGADES: "UPDATE_BRIGADES",
    UPDATE_BATTALIONS: "UPDATE_BATTALIONS",
    UPDATE_COMPANIES: "UPDATE_COMPANIES",
    UPDATE_TYPES: "UPDATE_TYPES",
    UPDATE_OUTLINES: "UPDATE_OUTLINES",
    UPDATE_RESULTS: "UPDATE_RESULTS",
    UPDATE_DESTINATIONS: "UPDATE_DESTINATIONS",
    UPDATE_CURRENT_STEP_SELECTED_INTERESTS: "UPDATE_CURRENT_STEP_SELECTED_INTERESTS",
    CLEAR_CURRENT_STEP_SELECTED_INTERESTS: "CLEAR_CURRENT_STEP_SELECTED_INTERESTS"
}